### ISSUE TITLE
Unavailable option can be taken 

### ISSUE THREAD

**Issue by Genne23v** [LostButton/my-button-ssg#1]
I tried with `node server.js -t` option. It seems it doesn't create HTML files but it shows the message `The HTML files have been saved to ./dist!`. I think it needs to show an error message instead.

**Comment by Genne23v** [comment]
Maybe just for me. `server.js ...` command does not work for me. I have to run `node server.js ...`

**Comment by Genne23v** [comment]
I tried `node server.js -i <FOLDER> -o temp` and `node server.js -i <folder> --output temp`. But it didn't create `temp` folder. And the message on terminal shows `The HTML files have been saved to ./dist!`.

**Comment by Genne23v** [comment]
it will be nicer to have indenting for child elements and line break on each element.

**Comment by CDPhu** [comment]
Fixed
